version: '3.3'

services:
  web:
    container_name: robot
    image: "node:14.5.0"
    working_dir: /home/node/app
    command: "yarn start"
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
